/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hr.edunova.horvat.view;

import com.toedter.calendar.JCalendar;
import hr.edunova.horvat.controller.ObradaGrupa;
import hr.edunova.horvat.model.Grupa;
import java.awt.BorderLayout;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author Josip
 */
public class Izbornik extends javax.swing.JFrame {

    /** Creates new form Izbornik */
    public Izbornik() {
        initComponents();
       jmNaslovGrana.setText(Aplikacija.NASLOV_APP);
        
        setTitle(Aplikacija.operater.getImeIPrezime());
       
      //if(!Aplikacija.operater.getUloga().equals("admin")){
        //     jmiOperateri.setVisible(false);
        //}
//        if(!Aplikacija.isAdmin()){
//          jmOperateri.setVisible(false);
//        }
        
       jmOperateri.setVisible(Aplikacija.isAdmin());
       
      
       //pripremiKalendar();
       pripremiGraf();
       pripremiKalendar();
       }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlKalendar = new javax.swing.JPanel();
        rbtnUkljuciKalendar = new javax.swing.JRadioButton();
        rbtnIskljuciKalendar = new javax.swing.JRadioButton();
        pnlGraf = new javax.swing.JPanel();
        tglGraf = new javax.swing.JToggleButton();
        jmGrana = new javax.swing.JMenuBar();
        jmNaslovGrana = new javax.swing.JMenu();
        jmSmjerovi = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmPolaznici = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmPredavaci = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jmGrupe = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jmOperateri = new javax.swing.JMenuItem();
        separator = new javax.swing.JPopupMenu.Separator();
        jmIzlaz = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        setSize(new java.awt.Dimension(400, 500));

        javax.swing.GroupLayout pnlKalendarLayout = new javax.swing.GroupLayout(pnlKalendar);
        pnlKalendar.setLayout(pnlKalendarLayout);
        pnlKalendarLayout.setHorizontalGroup(
            pnlKalendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
        );
        pnlKalendarLayout.setVerticalGroup(
            pnlKalendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );

        rbtnUkljuciKalendar.setText("On");
        rbtnUkljuciKalendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnUkljuciKalendarActionPerformed(evt);
            }
        });

        rbtnIskljuciKalendar.setText("Off");
        rbtnIskljuciKalendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnIskljuciKalendarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlGrafLayout = new javax.swing.GroupLayout(pnlGraf);
        pnlGraf.setLayout(pnlGrafLayout);
        pnlGrafLayout.setHorizontalGroup(
            pnlGrafLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );
        pnlGrafLayout.setVerticalGroup(
            pnlGrafLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 156, Short.MAX_VALUE)
        );

        tglGraf.setText("tglGraf");
        tglGraf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglGrafActionPerformed(evt);
            }
        });

        jmNaslovGrana.setText("NASLOV");

        jmSmjerovi.setText("Smjer");
        jmNaslovGrana.add(jmSmjerovi);
        jmNaslovGrana.add(jSeparator1);

        jmPolaznici.setText("Polaznici");
        jmNaslovGrana.add(jmPolaznici);
        jmNaslovGrana.add(jSeparator2);

        jmPredavaci.setText("Predavaci");
        jmNaslovGrana.add(jmPredavaci);
        jmNaslovGrana.add(jSeparator3);

        jmGrupe.setText("Grupe");
        jmNaslovGrana.add(jmGrupe);
        jmNaslovGrana.add(jSeparator4);

        jmOperateri.setText("Operateri");
        jmNaslovGrana.add(jmOperateri);
        jmNaslovGrana.add(separator);

        jmIzlaz.setText("Izlaz");
        jmIzlaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmIzlazActionPerformed(evt);
            }
        });
        jmNaslovGrana.add(jmIzlaz);

        jmGrana.add(jmNaslovGrana);

        setJMenuBar(jmGrana);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlGraf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tglGraf)
                        .addGap(10, 10, 10)
                        .addComponent(rbtnUkljuciKalendar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnIskljuciKalendar))
                    .addComponent(pnlKalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnUkljuciKalendar)
                    .addComponent(rbtnIskljuciKalendar)
                    .addComponent(tglGraf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlKalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlGraf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(138, 138, 138))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmIzlazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmIzlazActionPerformed
      dispose();
    }//GEN-LAST:event_jmIzlazActionPerformed

    private void rbtnUkljuciKalendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnUkljuciKalendarActionPerformed
        pnlKalendar.setVisible(true);
      if(rbtnUkljuciKalendar.isSelected()){
         rbtnIskljuciKalendar.setSelected(false);
      }
            
        
    }//GEN-LAST:event_rbtnUkljuciKalendarActionPerformed

    private void rbtnIskljuciKalendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnIskljuciKalendarActionPerformed
        pnlKalendar.setVisible(false);
         if(rbtnIskljuciKalendar.isSelected()){
           rbtnUkljuciKalendar.setSelected(false);
         }
    }//GEN-LAST:event_rbtnIskljuciKalendarActionPerformed

    private void tglGrafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglGrafActionPerformed
      
    }//GEN-LAST:event_tglGrafActionPerformed

   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenuBar jmGrana;
    private javax.swing.JMenuItem jmGrupe;
    private javax.swing.JMenuItem jmIzlaz;
    private javax.swing.JMenu jmNaslovGrana;
    private javax.swing.JMenuItem jmOperateri;
    private javax.swing.JMenuItem jmPolaznici;
    private javax.swing.JMenuItem jmPredavaci;
    private javax.swing.JMenuItem jmSmjerovi;
    private javax.swing.JPanel pnlGraf;
    private javax.swing.JPanel pnlKalendar;
    private javax.swing.JRadioButton rbtnIskljuciKalendar;
    private javax.swing.JRadioButton rbtnUkljuciKalendar;
    private javax.swing.JPopupMenu.Separator separator;
    private javax.swing.JToggleButton tglGraf;
    // End of variables declaration//GEN-END:variables

     private void pripremiGraf(){
       
         ObradaGrupa obradaGrupa = new ObradaGrupa();
		
          DefaultPieDataset dataset = new DefaultPieDataset();
          
          for(Grupa g: obradaGrupa.getPodaci()){
              dataset.setValue(g.getNaziv(),  g.getPolaznici().size());
          }
        
          
         JFreeChart chart = ChartFactory.createPieChart(
                 "Broj polaznika po grupama",
                 dataset,
                 true,
                 true,
                 false);
         
         ChartPanel cp = new ChartPanel(chart); 
         
        pnlGraf.setLayout(new BorderLayout());
        pnlGraf.add(cp);
        pnlGraf.validate();

                
     }
    private void pripremiKalendar(){
        
        pnlKalendar.setLayout(new BorderLayout());
         
        JCalendar cal = new JCalendar();
        
        pnlKalendar.setLayout(new BorderLayout());
        pnlKalendar.add(cal,BorderLayout.CENTER);
        pnlKalendar.validate();
        
       }
     
       
    
}
