/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hr.edunova.horvat.view;

import java.awt.BorderLayout;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author Josip
 */
public class Izbornik extends javax.swing.JFrame {

    /** Creates new form Izbornik */
    public Izbornik() {
        initComponents();
       jmNaslovGrana.setText(Aplikacija.NASLOV_APP);
        
        setTitle(Aplikacija.operater.getImeIPrezime());
       
      //if(!Aplikacija.operater.getUloga().equals("admin")){
        //     jmiOperateri.setVisible(false);
        //}
//        if(!Aplikacija.isAdmin()){
//          jmOperateri.setVisible(false);
//        }
        
       jmOperateri.setVisible(Aplikacija.isAdmin());
       
       pnlGraf.setLayout(new BorderLayout());
       
      XYSeries series = new XYSeries("XY Chart");
		XYSeriesCollection dataset = new XYSeriesCollection(series);
		JFreeChart chart = ChartFactory.createTimeSeriesChart("Testing Chart", "Date", "Average Profit", dataset);
		
                ChartPanel cp = new ChartPanel(chart);
                
                pnlGraf.setLayout(new BorderLayout());
                pnlGraf.add(cp,BorderLayout.CENTER);
                pnlGraf.validate();
		
                
                
		
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGraf = new javax.swing.JPanel();
        jmGrana = new javax.swing.JMenuBar();
        jmNaslovGrana = new javax.swing.JMenu();
        jmSmjerovi = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmPolaznici = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmPredavaci = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jmGrupe = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jmOperateri = new javax.swing.JMenuItem();
        separator = new javax.swing.JPopupMenu.Separator();
        jmIzlaz = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout pnlGrafLayout = new javax.swing.GroupLayout(pnlGraf);
        pnlGraf.setLayout(pnlGrafLayout);
        pnlGrafLayout.setHorizontalGroup(
            pnlGrafLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );
        pnlGrafLayout.setVerticalGroup(
            pnlGrafLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        jmNaslovGrana.setText("NASLOV");

        jmSmjerovi.setText("Smjer");
        jmNaslovGrana.add(jmSmjerovi);
        jmNaslovGrana.add(jSeparator1);

        jmPolaznici.setText("Polaznici");
        jmNaslovGrana.add(jmPolaznici);
        jmNaslovGrana.add(jSeparator2);

        jmPredavaci.setText("Predavaci");
        jmNaslovGrana.add(jmPredavaci);
        jmNaslovGrana.add(jSeparator3);

        jmGrupe.setText("Grupe");
        jmNaslovGrana.add(jmGrupe);
        jmNaslovGrana.add(jSeparator4);

        jmOperateri.setText("Operateri");
        jmNaslovGrana.add(jmOperateri);
        jmNaslovGrana.add(separator);

        jmIzlaz.setText("Izlaz");
        jmIzlaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmIzlazActionPerformed(evt);
            }
        });
        jmNaslovGrana.add(jmIzlaz);

        jmGrana.add(jmNaslovGrana);

        setJMenuBar(jmGrana);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGraf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGraf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmIzlazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmIzlazActionPerformed
      dispose();
    }//GEN-LAST:event_jmIzlazActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Izbornik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Izbornik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Izbornik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Izbornik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Izbornik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenuBar jmGrana;
    private javax.swing.JMenuItem jmGrupe;
    private javax.swing.JMenuItem jmIzlaz;
    private javax.swing.JMenu jmNaslovGrana;
    private javax.swing.JMenuItem jmOperateri;
    private javax.swing.JMenuItem jmPolaznici;
    private javax.swing.JMenuItem jmPredavaci;
    private javax.swing.JMenuItem jmSmjerovi;
    private javax.swing.JPanel pnlGraf;
    private javax.swing.JPopupMenu.Separator separator;
    // End of variables declaration//GEN-END:variables

}
